Repository CATcher-org/catcher-org.github.io, pull requests merged in 2023-01, with the labels that each got.

#20 move dev commands to relevant sections
  dg/project-management.md
  dg/setting-up.md
  dg/testing.md
Labels: s.ToMerge

#22 Add devcontainer support
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  README.md
  assets/dev-container-recommended-ext.png
  assets/open-a-remote-window.png
  assets/reopen-in-container.png
Labels: s.ToReview

#24 Update Setting up Guide to date
  README.md
  dg/project-management.md
  dg/setting-up.md
Labels: documentation, s.ToReview
